name: Deploy App

on:
  push:
    branches:
      - develop
      - main

jobs:
  preprod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/develop'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy App
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd ${{ secrets.FOLDER }} && make deploy'
  
  prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/main'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}

    - name: Deploy App
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.PROD_SSH_USER }}@${{ secrets.SSH_HOST }} 'cd ${{ secrets.PROD_FOLDER }} && make deploy'
